[tasks.clippy]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.clippy-fix]
workspace = false
command = "cargo"
args = [
	"clippy",
	"--fix",
	"--allow-dirty",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.fmt]
workspace = false
dependencies = [
	"fmt-rust",
	"fmt-taplo",
]

[tasks.fmt-rust]
workspace = false
command = "cargo"
toolchain = "nightly"
args = [
	"fmt",
	"--all",
]

[tasks.fmt-taplo]
workspace = false
command = "taplo"
args = ["fmt"]

[tasks.nextest]
workspace = false
command = "cargo"
args = [
	"nextest",
	"run",
	"--workspace",
	"--all-targets",
	"--all-features",
]

[tasks.udeps]
workspace = false
command = "cargo"
toolchain = "nightly"
args = [
	"udeps",
	"--workspace",
	"--all-targets",
	"--all-features",
]
